### ISSUE TITLE
Allow one to turn off Unicode support for target files

### ISSUE THREAD

**Issue by JustinCappos** [theupdateframework/python-tuf#168]
There should also be a setting to disable unicode entirely.   Let's add this to root.txt.

**Comment by lukpueh** [comment]
@JustinCappos, is this feature request still valid? If so I suggest we move the issue to the spec issue tracker. Please also see a rehash of the unicode discussion in #61.

**Comment by JustinCappos** [comment]
I'm ambivalent after reading #61.  We could turn it off entirely, close the issue as wont-fix or take another path.  Any strong thoughts from others?

**Comment by trishankatdatadog** [comment]
Yes, I'm for turning it off by default (so I guess we enforce only printable ASCII), but allow integrators to get full-blown Unicode if they want it. This does make the codebase slightly more complicated (reusable functions with if-else statements).

**Comment by MVrachev** [comment]
So, we agree that we are turning off Unicode by default?
Do we want to close this issue and lead the discussion on issue https://github.com/theupdateframework/tuf/issues/61?

**Comment by trishankatdatadog** [comment]
Do we even support Unicode at all?

**Comment by jku** [comment]
I'm not sure what is being referred to with "unicode support" (I think the issue should be a little clearer on this) but if it means 
* supporting utf-8 in target names in repository metadata 
* adding files with utf-8 file names to a repo  with e.g. repository_tool
* downloading these targets with the client

that does seem to work with python3.

```
>>> target = updater.get_one_valid_targetinfo('emoji/😬')
>>> targets = updater.updated_targets([target], '.')
>>> updater.download_target(targets[0], '.')
>>> 
jku@luna:~$ ls emoji/
😬
jku@luna:~$ 
```
In the metadata file the target name is `"emoji/\ud83d\ude2c"`, the url client downloads is `emoji/<HASH>.%F0%9F%98%AC`.

I think not supporting unicode at all in 2020 requires really good reasons: people do use languages other than english in their filenames.

**Comment by trishankatdatadog** [comment]
Agreed. I'm not convinced TUF should solve typosquatting.

**Comment by jku** [comment]
> I'm not sure what is being referred to with "unicode support" (I think the issue should be a little clearer on this)

Closing, please reopen if there are more details.
