### ISSUE TITLE
Create static metadata that demonstrates attacks

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/python-tuf#360]
We should expand the [Security](https://github.com/theupdateframework/tuf/blob/develop/SECURITY.md) page to include static metadata that simulates known attacks (e.g., replay attack, freeze attack, etc.).  This metadata can be fed to other implementations to verify that they correctly handle these attacks.

**Comment by vladimir-v-diaz** [comment]
The repository management document was updated to demonstrate some of the attacks TUF detects: https://github.com/theupdateframework/tuf/tree/526d7507fa21c71b5f938557f982f757241d3e98/tuf#blocking-malicious-updates

**Comment by awwad** [comment]
Updated security page link: https://github.com/theupdateframework/tuf/blob/develop/docs/SECURITY.md

**Comment by lukpueh** [comment]
The section in the repository management document mentioned above was later moved to an attack demo document, which was recently removed as it had become severely outdated. #1798 suggests to reinstate an up-to-date version of the document. So I'd say we can close here. (I will add a note to #1798 about feeding demo data into other implementations)
