### ISSUE TITLE
Fast Forward Attack Recovery Necessary (Mercury)

### ISSUE THREAD

**Issue by awwad** [theupdateframework/python-tuf#414]
#### TLDR
The Mercury paper noted that a fast-forward attack is possible against a TUF repository if the timestamp and snapshot role keys (the typically online keys) are compromised, due to the way that replay attack protection works. These fast-forward attacks should be resolved by resetting the highest-seen-valid-version-number cache on the client side when a change has been made in root.json to the snapshot role after a compromise is resolved. This is not currently done in TUF.

#### Replay attack background:
Replay attacks are prevented by having a client refuse to accept versions of a given metadata role file smaller than the highest that they have ever seen listed for that role in a valid snapshot.json metadata file.)

#### The Fast Forward Attack:
In this "fast forward" attack, the attacker employs compromised snapshot and timestamp keys to sign a snapshot metadata file that sets the version numbers listed in the snapshot metadata above the version number of the most recent version of the metadata files, or perhaps at the maximum version value. This results in a denial of service: clients who accept this snapshot metadata will not accept any metadata files with versions less than these arbitrarily inflated version numbers. (e.g. the malicious snapshot might list the version for root as 2048 when the most recent root version is actually 16.)

#### Recovery:
Once the compromised server is recovered, it is necessary to change the timestamp and snapshot keys since the old keys have been exposed. At this point, in order to allow clients who accepted the malicious snapshot.json file to update metadata again (to recover from the fast forward attack), it is necessary to reset the version numbers saved by the updater as the highest-seen-valid-version-number. (This is an attribute of the `Repository` object, `versioninfo`.)

Note that this must be done *after* signature validation of a new root file, of course, so that attackers without root keys can't cause snapshot reset to enable replay attacks

#### Code Delta
This change should be made to [tuf.client.updater.Updater::_update_metadata(), within the `if` block at the end of the method](https://github.com/theupdateframework/tuf/blob/5ba82fe9ddddc04f9ba094d4744e62733f64fae0/tuf/client/updater.py#L1403-L1405). There, it should compare canonicalized versions of `self.metadata['previous']['root']['roles']['snapshot']` and `self.metadata['current']['root']['roles']['snapshot']`. If they are not equal, we should reset the `versioninfo` cache.

#### Drawbacks
This will err on the side of resetting version numbers more often than necessary, which slightly increases the vulnerability to replay attacks *only* in edge cases in which there is a change to the snapshot role entry in root.json that does _not_ make it impossible to replay old metadata. (These are edge cases, because normally, after a compromise, repository management will want to make use of the old snapshot key inadequate to validate snapshot data.) Here is an example:
 - There has been no compromise, but a new key is added to the snapshot role and the old key is not removed and the threshold is not increased. Client-side replay protection now drops the minimum acceptable version to 0, and replay attacks become possible using old snapshots signed with the old key.

#### Note on TAP 5
Changes from TAP 5 will not affect this behavior, because if the changes are made as recommended above, it is not necessary for a timestamp validation to fail first.

**Comment by trishankkarthik** [comment]
We'll attach the paper here when it's published

**Comment by trishankkarthik** [comment]
By the way, what does the TUF client do when the keys for a role has been rotated? By rotation, I mean that no set containing a threshold of previous keys can be used to verify the latest metadata. @JustinCappos and I think that the previous metadata file should be deleted. This is done to prevent fast-forward attacks, where attackers have arbitrarily increased the version number in the previous metadata file.

Cc: @vladimir-v-diaz

**Comment by vladimir-v-diaz** [comment]
I think we delete metadata that cannot be verified when attempting to update it (e.g., a trusted set of keys cannot validate it).  There is currently a TODO stating that security implications of deleting metadata in this manner have not been fully investigated. Some of this code might change slightly when this issue (#414) is fully implemented, and we'll make sure that metadata is deleted as needed to prevent fast-forward attacks.

See the code below for how metadata that cannot be updated is deleted...

https://github.com/theupdateframework/tuf/blob/develop/tuf/client/updater.py#L1565-L1575

```Python
 try:
      self._update_metadata(metadata_role, upperbound_filelength,
                            expected_versioninfo['version'], compression)

 except:
      # The current metadata we have is not current but we couldn't get new
      # metadata. We shouldn't use the old metadata anymore.  This will get rid
      # of in-memory knowledge of the role and delegated roles, but will leave
      # delegated metadata files as current files on disk.
      #
      # TODO: Should we get rid of the delegated metadata files?  We shouldn't
      # need to, but we need to check the trust implications of the current
      # implementation.
      self._delete_metadata(metadata_role)
      logger.error('Metadata for ' + repr(metadata_role) + ' cannot be updated.')
      raise
```

**Comment by ivanayov** [comment]
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

**More details**

Current source code (and upcoming 1.0 release) only contains the modern components

* a low-level Metadata API (`tuf.api`) and
* `tuf.ngclient` that implements the client workflow,

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

There are [fast forward recovery tests](https://github.com/theupdateframework/python-tuf/blob/215073e250605be01eebcc99a306df961a9d7408/tests/test_updater_top_level_update.py) available. Probably consider reopening if those are not sufficient.
