### ISSUE TITLE
Improve documentation on roles and delegations

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/python-tuf#446]
The use of roles and delegations in TUF has been a source of confusion in the past.  We should improve their documentation to better explain how they are often and should be used in production.

**Comment by lukpueh** [comment]
I'm closing this as too unspecific. The TUF metadata classes in [python-tuf 1.0.0](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) map closely to how they are represented in the specification. Role and delegation entities should be easily distinguishable.
