### ISSUE TITLE
Should the specification restrict the format of rolenames listed in metadata?

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/python-tuf#456]
The specification does not set any restrictions on the rolenames listed in metadata.  For example, these rolenames may include unicode and other special characters.  We can leave it up to adopters to set these restrictions for their particular implementation, or we can require a set of restrictions by default for cases that we know can lead to problems.

**Comment by JustinCappos** [comment]
This is tough.  Any implementation should be careful about what it permits,
but I don't know that it is our role to force them to not use certain
characters.

Is having best practices around which characters are allowed a good way to
handle this?

**Comment by jku** [comment]
I'll document the current situation in python-tuf and then close this: I agree that the specification could be a lot better in this regard but that's not a python-tuf issue.

python-tuf handles rolenames as follows:
* any string is an acceptable rolename
* rolenames are not expected to be valid parts of a file path: e.g. the client percent encodes the rolename before using it as a filename
* as a clarification to those two points, the "ROLENAME.json" key in targets delegations is still expected to be the raw string with an extension added to the end (I consider this a specification bug, the key should be just "ROLENAME"). This means the key does not necessarily match the filename that is actually used to store the metadata.
