### ISSUE TITLE
Current usage of snapshot does permit removing a role

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/python-tuf#476]
Consider the following:

Some repo has a delegation `foo` that has been marked as inactive for not uploading a package for 1 year. The repo wants to move all those targets into some catch-all `unattended` role and remove `foo` from the snapshot. This is currently not supported. A malicious `snapshot` role could just remove all the known roles, then on the next update serve whatever versions it wants.

A possible solution to this is for all clients to keep a local "snapshot cache" that tracks the latest known version for targets/delegation metadata. This version is insert only and is only wiped after a root rotation. Clients wouldn't check that `x.snapshot.json` matches `(x-1).snapshot.json` but they would check it against the cache instead, then update it.

**Comment by jku** [comment]
Is the title missing a "not"?

Situation as I understand it currently:
* specification explicitly says delegated roles cannot be removed 
* as an exception to this, doing a "targets fast-forward attack recovery" (in other words fully rotating the signing keys of the delegating metadata) allows removal of delegated roles as it disables the rollback protections 
* Current python-tuf implementation is compliant with the specification (both points above)

So... I think there's no issue in python-tuf: I'll close this issue but please reopen if there is a misunderstanding here.
