### ISSUE TITLE
Misleading: "unsafely update root"

### ISSUE THREAD

**Issue by awwad** [theupdateframework/python-tuf#548]
Currently, tuf/client/updater.py refers to the "unsafe" updating of root in two scenarios:
1. the current root file is expired, but will still be used to validate a new root file
2. a new snapshot file could not be validated, and root will be updated even though we don't have snapshot's data about a root metadata file)

I haven't checked the logic in the code regarding scenario 1.

Scenario 2, however, is misleading. This is not unsafe, as snapshot's vouching for the root file is not of real security import - which is why we're okay with removing the root listing in snapshot (as a [peripheral part of TAP 5](https://github.com/theupdateframework/taps/blob/master/tap5.md#changes-to-the-snapshot-metadata-file)).

It would be best, I think, to clean up the optional arguments, debug messages, and code comments to not leave this misleading impression.

(The unsafely_update... argument is also used to prevent an infinite loop of root checks - it's the mechanism used to try-again only once.)

**Comment by vladimir-v-diaz** [comment]
I think updating Root "unsafely" is currently misleading mainly because of the changes made to the update procedure, where  (1) new versions of Root must be updated in order (1.root.json -> 2.root.json, etc.) (2) Root must be updated before any of the other top-level roles, and (3) a new Root must be signed by a threshold of trusted keys set by the previous version.

**Comment by awwad** [comment]
Just so things are clear in case someone's assigned to deal with this:

1. I don't think that (1) and (2) impacted the safety of skipping snapshot-based validation of a root file. IIUC, in their absence, it remains as safe to try to update root as long as you are validating based on the trusted root information (which occurs even with `unsafely_update...` set). That is, I don't think there's much if any security impact to checking the root hash in snapshot whether you're trying to go from root v1 to v6 directly or v1 to v2. v1 to v6 directly may fail if keys+threshold has changed too much, but the existence of a root hash in snapshot doesn't impact that.
2. I don't think (3) resulted from a change, unless it was from well before I was around, long before any TAPs. (3) is absolutely critical and not having it at any point would demolish security guarantees. (TBC, it remains the case whether or not the unsafely flag is on.)

The ask here is to clarify this segment of code, renaming the argument and adjusting comments so that it does not confuse implementers / maintainers, and IIRC probably restructuring it so that the try-twice root validation doesn't occur.

**Comment by jku** [comment]
closing:
* root has not been part of snapshot for a while now so the core issue does not exist
* ngclient also does not use the misleading naming "unsafe update"
