### ISSUE TITLE
Support hardware security modules or signing metadata externally

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/python-tuf#569]
Note: The following issue has been reported by @trishankatdatadog and drafted by @vladimir-v-diaz.

**Description of issue or feature request**:

The repository tool should support hardware security modules, like Yubikey.  If not direct support, the tool should at least provide methods that do not require writing and loading keys directly from disk.

Note: Functionality was recently added where a user can append signatures to metadata.  See
https://github.com/theupdateframework/tuf/pull/474.  We should investigate whether this functionality addresses this issue or not.

**Current behavior**:

```
>>> private_targets_key = import_rsa_privatekey_from_file("keystore/targets_key")
Enter a password for the encrypted RSA key:
```

**Expected behavior**:

For example,

```
>>> repository.root.sign_with_hardware_key()
```

**Comment by trishankatdatadog** [comment]
I haven't looked into this deeply, but I think there are two kinds of support.

One way is to use Yubikey / Nitrokey to store a single GPG signing subkey. Then, the TUF repository / developer tool should be able to use something like ```python-gnupg``` to sign with GPG, which in turn should interface with the Yubikey / Nitrokey using a smartcard standard. (I have written an article on "how to use Yubikey 4c Nano for GPG and SSH on macOS" which I hope to release soon.) I hear from @SantiagoTorres that GPG support is coming soon to ```securesystemslib```.

Another way would be to add support for multiple signing keys stored on Yubikey / Nitrokey HSMs. This might require a bit more work, and might even largely be out of the scope of the TUF repository / developer tool. See [examples of using Nitrokey HSM with PKCS #11](https://python-pkcs11.readthedocs.io/en/latest/opensc.html).

We should certainly test whether TUF works well with either setup "out of the box."

**Comment by dgreisen** [comment]
Hello. We are building an implementation on TUF, and we would like to use Yubikeys to securely store encryption keys. Has there been any further work on this? If not, we will likely attempt to use #474 and gpg through subprocess. We are also happy to do the work to get the functionality into core if there is a better way.

**Comment by trishankatdatadog** [comment]
@dgreisen That might work. [in-toto](in-toto.io) provides an option to use GPG, and we are thinking about moving that functionality to [securesystemslib](https://github.com/secure-systems-lab/securesystemslib/), shared between tuf and in-toto, so that both can use GPG if they want to. That might come in later in the line, though, and we would appreciate if someone would help us do this :)

**Comment by danixeee** [comment]
Hello, we have copied and slightly modified GPG implementation from [in-toto](https://github.com/in-toto/in-toto) to [securesystemslib](https://github.com/secure-systems-lab/securesystemslib) to support signing TUF metadata externally.

Initial PR is here: https://github.com/secure-systems-lab/securesystemslib/pull/163.

**Comment by joshuagl** [comment]
there's work in sslib to support HSM https://github.com/secure-systems-lab/securesystemslib/pull/229

**Comment by lukpueh** [comment]
Superseded by #1912
