### ISSUE TITLE
Deal with Unicode

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/python-tuf#61]
TUF needs to be able to consistently handle Unicode, especially since there are PyPI packages with names like "☃".

Vlad:
Metadata for Python Software Packages v2.0
http://hg.python.org/peps/file/ea3d93e40e02/pep-0426.txt#l596

Metadata for Python Software Packages
http://www.python.org/dev/peps/pep-0241

Metadata for Python Software Packages v1.1
http://www.python.org/dev/peps/pep-0314/

Metadata for Python Software Packages 1.2
http://www.python.org/dev/peps/pep-0345/

The Python Package Index (PyPI) Documentation
http://docs.python.org/2/distutils/packageindex.html

[Distutils] New Restrictions on Package Names
http://mail.python.org/pipermail/distutils-sig/2013-May/020807.html

[Distutils] Proposal: Restrict the characters in a project name
http://mail.python.org/pipermail/distutils-sig/2013-May/020701.html

**Comment by trishankatdatadog** [comment]
Note: we should check whether this was done @mnm678 @lukpueh

**Comment by lukpueh** [comment]
Looks like unicode in delegated targets **role names** and target **file names** does work out of the box on Python 3 (as per empirical evidence gathered with this [tuf_with_unicode.py](https://gist.github.com/lukpueh/dae46ed4fc51cd55bb90d69d596e197c)-script).

Given that this has not been an issue in the past 7 years and Python 2 is retiring, can we close this as *won't-fix*? cc @trishankatdatadog, @mnm678, @JustinCappos.

Moreover, PyPI will not (and nobody else should) need unicode role names, and also does not need unicode target file names. @ewdurbin, @woodruffw, can you confirm that the [distribution name spec](https://www.python.org/dev/peps/pep-0426/#name) is accurate and being followed? Thanks!

**Comment by mnm678** [comment]
I agree. If this is not an issue with existing implementations, the python 3 support should be sufficient.

**Comment by trishankatdatadog** [comment]
I think that would severely restrict TUF usage in practice. If people are worried about [Unicode spoofing attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack), they should handle it on a layer above TUF.

**Comment by ewdurbin** [comment]
> @ewdurbin, @woodruffw, can you confirm that the distribution name spec is accurate and being followed?

I'll need to review warehouse code and existing files to be sure, but will try to get confirmation on this soon.

**Comment by lukpueh** [comment]
> I think that would severely restrict TUF usage in practice.

Would you mind elaborating, @trishankatdatadog?

**Comment by woodruffw** [comment]
> I'll need to review warehouse code and existing files to be sure, but will try to get confirmation on this soon.

To add to this: I *believe* that Warehouse enforces PEP 426 at the DB level, i.e. has a virtual column whose value is the normalized dist name for each package.

**Comment by trishankatdatadog** [comment]
> Would you mind elaborating, @trishankatdatadog?

It is conceivable that some package repositories allow for using Unicode in package names?

**Comment by lukpueh** [comment]
So you say we should add unicode support for TUF on Python2, @trishankatdatadog?

**Comment by trishankatdatadog** [comment]
Not Python2, sorry, but Python3. Also, the Unicode support should ideally be conditional: I guess by default we can enforce ASCII (too restrictive for some), but the codebase should handle Unicode if the user asks for it. Makes the codebase more complicated, I know...

**Comment by jku** [comment]
Current state from python-tuf perspective :
* rolenames can be unicode
* rolenames should never be used as local file paths (and they are not in ngclient)
* targetpaths are expected to be valid url parts (so percent encoded)
* targetpaths are not used as local file paths by default but a specific client could decide to do this

If there's something specific that needs to be done, let's continue in a more specific issue
