### ISSUE TITLE
Request: log messages to user/application logger

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/python-tuf#750]
**Description of issue or feature request**:

It would be nice if applications may pass in loggers to TUF so that update messages are logged there instead.

**Current behavior**:

Log message are directed to internal file handlers, or the console.

**Requested behavior**:

There should be an option to also log TUF's logger messages to application's logger.

**Comment by jku** [comment]
I'm going to close this: 
* as far as I can tell the `logging` logger hierarchy gives the application full (if not always the most ergonomic) control
* I think library modules should not make decisions on where to log: this is an application choice

Please reopen if it sounds like I'm not considering a use case you have in mind.
